version: "3.6"

services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./../templates/default/dist:/usr/share/nginx/html
      - C:\Dev\personal\rniemand.github.io\_posts:/usr/share/nginx/html/_posts
      - C:\Dev\personal\rniemand.github.io\_tabs:/usr/share/nginx/html/_tabs
      - C:\Dev\personal\rniemand.github.io\assets:/usr/share/nginx/html/assets
      - ./../templates/_rnssg:/usr/share/nginx/html/_rnssg
    ports:
      - 8080:80
